export const API_URL='http://localhost:8000/api/v1'
export const LOGIN_REQUEST='LOGIN_REQUEST';
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_FAILED='LOGIN_FAILED';
export const REGISTER_SUCCESS='REGISTER_SUCCESS';
export const REGISTER_FAILED='REGISTER_FAILED';
export const LOGOUT_REQUEST='LOGOUT_REQUEST';
export const GET_PENDING_ACCOUNTS_SUCCESS='GET_PENDING_ACCOUNTS_SUCCESS';
export const GET_PENDING_ACCOUNTS_FAILED='GET_PENDING_ACCOUNTS_FAILED';
export const UPDATE_USER_ACCOUNT_SUCCESS='UPDATE_USER_ACCOUNT_SUCCESS';
export const UPDATE_USER_ACCOUNT_FAILED='UPDATE_USER_ACCOUNT_FAILED';
export const GET_ALL_USERS_SUCCESS='GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAILED='GET_ALL_USERS_FAILED';
export const DEACTIVATE_USER_SUCCESS='DEACTIVATE_USER_SUCCESS';
export const DEACTIVATE_USER_FAILED='DEACTIVATE_USER_FAILED'



//--------------------Profile---------------------------//
export const UPLOAD_PROFILE_IMAGE_SUCCESS='UPLOAD_PROFILE_IMAGE_SUCCESS'
export const UPLOAD_PROFILE_IMAGE_FAILED='UPLOAD_PROFILE_IMAGE_FAILED'
export const UPDATE_PROFILE_SUCCESS='UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILED='UPDATE_PROFILE_FAILED';
export const GET_USER_PROFILE_SUCCESS='GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAILED='GET_USER_PROFILE_FAILED'